[package]
name = "ajuna-primitives"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
ajuna-payment-handler = { workspace = true }
# Substrate - SCALE codec
parity-scale-codec = { workspace = true, features = [ "derive", "max-encoded-len" ] }
scale-info         = { workspace = true, features = [ "derive" ] }
sp-std             = { workspace = true }

# Substrate frame
frame-support = { workspace = true }

[features]
default = ["std"]
std = [
    "ajuna-payment-handler/std",
    "frame-support/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-std/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"ajuna-payment-handler/runtime-benchmarks"
]
