pub const ASSETS_NOT_ALL_SAME_TYPE: u8 = 100;
pub const ASSET_TYPE_NOT_FOUND_IN_ACCOUNT: u8 = 101;
pub const ASSET_TYPE_ALREADY_IN_ACCOUNT: u8 = 102;

pub const ASSET_COULD_NOT_RECEIVE_FUNDS: u8 = 150;
pub const ASSET_COULD_NOT_WITHDRAW_FUNDS: u8 = 151;
pub const ASSET_COULD_NOT_WITHDRAW_PLAY_FEE: u8 = 152;
pub const ASSET_COULD_NOT_RECEIVE_PLAY_FEE: u8 = 153;
pub const ASSET_COULD_NOT_WITHDRAW_MAX_REWARD: u8 = 154;
pub const ASSET_COULD_NOT_RECEIVE_MAX_REWARD: u8 = 155;
pub const ASSET_COULD_NOT_WITHDRAW_SPIN_REWARD: u8 = 156;
pub const ASSET_COULD_NOT_RECEIVE_SPIN_REWARD: u8 = 157;

pub const COULD_NOT_PERFORM_MACHINE_SPINS: u8 = 160;

pub const MACHINE_CANNOT_RENT_MORE_SEATS: u8 = 170;
pub const SEAT_IS_NOT_LINKED_TO_PLAYER: u8 = 171;
pub const SEAT_RESERVATION_HAS_EXPIRED: u8 = 172;
pub const SEAT_IS_NOT_LINKED_TO_SPECIFIED_PLAYER: u8 = 173;
pub const SEAT_HAS_NO_FUNDS: u8 = 174;
pub const SEAT_RESERVATION_IS_NOT_VALID: u8 = 175;
pub const SEAT_IS_NOT_LINED_TO_MACHINE: u8 = 176;
pub const MACHINE_HAS_NO_LINKED_SEATS: u8 = 177;
pub const SEAT_IS_STILL_LINKED_TO_PLAYER: u8 = 178;
pub const MACHINE_STILL_HAS_LINKED_SEATS: u8 = 177;

pub const ASSET_NOT_FOUND: u8 = 200;
pub const ASSET_SCORE_NOT_ENOUGH: u8 = 201;
pub const ASSET_TYPE_NOT_VALID: u8 = 202;
pub const ASSET_VARIANT_IS_NOT_PLAYER: u8 = 203;
pub const ASSET_VARIANT_IS_NOT_MACHINE: u8 = 204;
pub const ASSET_VARIANT_IS_NOT_HUMAN: u8 = 205;
pub const ASSET_VARIANT_IS_NOT_TRACKER: u8 = 206;
pub const ASSET_VARIANT_IS_NOT_SEAT: u8 = 207;
