pub const ASSETS_NOT_ALL_SAME_TYPE: u8 = 100;
pub const ASSET_TYPE_NOT_FOUND_IN_ACCOUNT: u8 = 101;
pub const ASSET_TYPE_ALREADY_IN_ACCOUNT: u8 = 102;

pub const ASSET_COULD_NOT_RECEIVE_FUNDS: u8 = 150;
pub const ASSET_COULD_NOT_WITHDRAW_FUNDS: u8 = 151;

pub const ASSET_NOT_FOUND: u8 = 200;
pub const ASSET_SCORE_NOT_ENOUGH: u8 = 201;
pub const ASSET_TYPE_NOT_VALID: u8 = 202;
pub const ASSET_VARIANT_IS_NOT_PLAYER: u8 = 203;
pub const ASSET_VARIANT_IS_NOT_MACHINE: u8 = 204;
pub const ASSET_VARIANT_IS_NOT_HUMAN: u8 = 205;
pub const ASSET_VARIANT_IS_NOT_TRACKER: u8 = 206;
pub const ASSET_VARIANT_IS_NOT_SEAT: u8 = 207;
