[package]
name = "example-transition"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
# Substrate - FRAME
frame-support      = { workspace = true }
sp-std             = { workspace = true }
# Substrate - Primitives
sp-core            = { workspace = true }
sp-runtime         = { workspace = true }
# Substrate - SCALE codec
parity-scale-codec = { workspace = true, features = [ "derive", "max-encoded-len" ] }
scale-info         = { workspace = true, features = [ "derive" ] }
# Ajuna
ajuna-primitives = { workspace = true }

# Sage
sage-api = { workspace = true}

[features]
default = ["std"]
std = [
    "frame-support/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "parity-scale-codec/std",
    "scale-info/std",
    # Sage
    "sage-api/std",
    # Ajuna
    "ajuna-primitives/std",
]
